# -*- coding: utf-8 -*-
"""TUGAS INTEGRAL METODE SCIPY

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p4Z1PuWGK-m9guoPIZiGZLjH0a9d5pBJ
"""

import numpy as np
from scipy import integrate
import matplotlib.pyplot as plt

# Parameter batas integral
x_start = 0  # Batas awal integral
x_stop = np.pi  # Batas akhir integral

# Definisikan fungsi integrasi
def integration_function(x):
    return x**2 * np.cos(x) + 3 * np.sin(2 * x)

# Menghitung integral menggunakan quad()
integral, _ = integrate.quad(integration_function, x_start, x_stop)
print("Nilai Integral:", integral)

# Membuat data untuk grafik
x_values = np.linspace(x_start, x_stop, 100)
y_values = integration_function(x_values)

# Plot kurva fungsi
plt.plot(x_values, y_values, label=r'$x^2 \cos(x) + 3 \sin(2x)$', color='blue')

# Isi area di bawah kurva sebagai hasil integral
plt.fill_between(x_values, y_values, color='skyblue', alpha=0.4)

# Menambahkan label dan judul grafik
plt.xlabel('x')
plt.ylabel('f(x)')
plt.title('Grafik Fungsi $x^2 \cos(x) + 3 \sin(2x)$ dan Area di Bawah Kurva')
plt.legend()

# Menampilkan grafik
plt.show()